repositories:
  directory: repo
  public:
    - spring-spigot
auth: "admin:admin"
spring:
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            PageNotFound: OFF